version: "3"
services:
  samba:
    image: dperson/samba
    environment:
      - "TZ=Asia/Tokyo"
      - "NMBD=True"
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"
    volumes:
      - ./data:/mnt/share:z
    command: >
      -s "share;/mnt/share;yes;no;yes;all;none;;comments1"
      -p
    # restart: unless-stopped
    restart: always
    stdin_open: true
    tty: true
